export type {
  Certification,
  Contact,
  Course,
  Education,
  Experience,
  Language,
  Link,
  Person,
  Project,
  Resume,
} from './schema';
export {
  certificationSchema,
  contactSchema,
  courseSchema,
  educationSchema,
  experienceSchema,
  languageSchema,
  linkSchema,
  metaSchema,
  personSchema,
  projectSchema,
  resumeSchema,
} from './schema';
